
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
